layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    - svm-vgg16
    - HaiCheViet.github.io

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  LeetCode: che_viet/
  linkedin: che-viet-hai-b9449711b/
  CV: file/d/1wwBl2ndD-AXd5Oe7-X8yPuTABKowmTTr/view
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/linux/linux.png

  - name: Tensorflow
    web_url: https://www.tensorflow.org/
    image_url: https://www.tensorflow.org/images/tf_logo_transp.png

  - name: Code quality
    web_url: https://github.com/topics/code-quality
    image_url: https://cdn-images-1.medium.com/fit/t/1600/480/1*RxTM94cmEWQo5LwcClll2w.jpeg
