layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects:
    - svm-vgg16
    - HaiCheViet.github.io
social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # instagram: yo_username
  # hackerrank: yourur_username
  LeetCode: che_viet/
  linkedin: hai-che/
  CV: file/d/1vIxM59cCpiwxQDD5Vl_rOVAcP_p3M8KE/view
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/linux/linux.png

  - name: Tensorflow
    web_url: https://www.tensorflow.org/
    image_url: https://www.tensorflow.org/images/tf_logo_transp.png

  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: https://d2908q01vomqb2.cloudfront.net/1b6453892473a467d07372d45eb05abc2031647a/2017/11/16/event_driven_sns_compute_slide01.png
